### ISSUE TITLE
may i send topic msg to its subscribers in broker directly but not publishing msg by mqtt client.

### ISSUE THREAD

**Issue by kexun** [256dpi/gomqtt#14]
hi gomqtt is a wonderful lib and i want to use it in my project. but we want to send alarm message to the subscriptions directly not by mqtt client publishing. since the MemoryBackend.temporarySessions is a private member, i can not use temporarySessions to lookupSubscription. can we extend another Publish(msg *packet.Message) function to help us to publish msg directly?

**Comment by 256dpi** [comment]
The `MemoryBackend` is a reference implementation intended to test the library. For any production broker I recommend to copy the code and adjust it to meet the desired standards. By doing that, you are free to integrate a method to queue messages to all connected clients.
