### ISSUE TITLE
Issue in 256dpi\gomqtt\topic\tree.go

### ISSUE THREAD

**Issue by eyauwag** [256dpi/gomqtt#16]
I have one question about the code in the path `github.com\256dpi\gomqtt\topic\tree.go`.
The `removeValue` function covers the value with the last value `n.values[len(n.values)-1]`. Is it correct?

```go
func (n *node) removeValue(value interface{}) {
	for i, v := range n.values {
		if v == value {
			// remove without preserving order
			n.values[i] = n.values[len(n.values)-1]
			n.values = n.values[:len(n.values)-1]
			break
		}
	}
}
```

The function string will ignore the first level value when i is 0. I think the function string is to print out the length of each leaf. So the fist level should not ignore.

```go
func (n *node) string(i int) string {
	str := ""

	if i != 0 {
		str = fmt.Sprintf("%d", len(n.values))
	}

	for key, node := range n.children {
		str += fmt.Sprintf("\n| %s'%s' => %s", strings.Repeat(" ", i*2), key, node.string(i+1))
	}

	return str
}
```

**Comment by 256dpi** [comment]
The `node.removeValue` functions replaces the to be removed value with the last value in the slice and resizes the slice to exclude the last value (this is standard Go technique to remove values from slices).  See https://github.com/golang/go/wiki/SliceTricks.

The root node will never contain any values and only children. Even when you do `tree.Add("", 1)` a child with the key `""` is created to store the values. Therefore the length of the root node is excluded when printing the tree. I added some commits to make this clearer.

**Comment by 256dpi** [comment]
I'm closing this as it is most likely resolved.
