### ISSUE TITLE
feature request: session on redis

### ISSUE THREAD

**Issue by nguyenthenguyen** [256dpi/gomqtt#2]
Hi! Thanks for good package!
I know this only packages for working with the MQTT protocol. If we wanna use on production we need some feature like persistence, clustering (hard to do) for HA application.  Could you add persistence package by implement session interface on redis package instead of memory?

**Comment by 256dpi** [comment]
Yes, implementing a session on redis would be a good idea for HA. However, the scope of this project is just the MQTT stuff and reference implementations of the interfaces in memory. But I'm always happy to link to other projects that provide further functionality.
