### ISSUE TITLE
fatal error：when wait the client closed, occur exception，help to solve it， thanks

### ISSUE THREAD

**Issue by yukunQin** [256dpi/gomqtt#20]
```
goroutine 372856 [running]:
runtime.throw(0x2ae05d2, 0x1e)
	runtime/panic.go:1116 +0x54 fp=0x400074b980 sp=0x400074b950 pc=0xf920b4
sync.throw(0x2ae05d2, 0x1e)
	runtime/panic.go:1102 +0x30 fp=0x400074b9a0 sp=0x400074b980 pc=0xf92050
sync.(*Mutex).unlockSlow(0x40003694e0, 0x40ffffffff)
	sync/mutex.go:196 +0xe4 fp=0x400074b9d0 sp=0x400074b9a0 pc=0xfcc3b4
sync.(*Mutex).Unlock(0x40003694e0)
	sync/mutex.go:190 +0x64 fp=0x400074b9f0 sp=0x400074b9d0 pc=0xfcc2a4
runtime.call32(0x0, 0x2badf08, 0x400157c548)
	runtime/asm_arm64.s:421 +0x74 fp=0x400074ba30 sp=0x400074b9f0 pc=0xfbf3c4
runtime.reflectcallSave(0x400074bba0, 0x2badf08, 0x400157c548, 0x8)
	runtime/panic.go:881 +0x48 fp=0x400074ba60 sp=0x400074ba30 pc=0xf91868
runtime.runOpenDeferFrame(0x400073db00, 0x400157c500, 0x400074bbe0)
	runtime/panic.go:855 +0x270 fp=0x400074bb20 sp=0x400074ba60 pc=0xf91740
panic(0x27b5c60, 0x3f91c90)
	runtime/panic.go:969 +0x11c fp=0x400074bbe0 sp=0x400074bb20 pc=0xf91a3c
runtime.panicmem(...)
	runtime/panic.go:212
runtime.sigpanic()
	runtime/signal_unix.go:717 +0x3c8 fp=0x400074bc10 sp=0x400074bbe0 pc=0xfa89d8
github.com/256dpi/gomqtt/broker.(*Client).Closed(...)
	github.com/256dpi/gomqtt@v0.10.4/broker/client.go:301
github.com/256dpi/gomqtt/broker.(*MemoryBackend).Setup(0x4000369480, 0x4001648000, 0x4000024040, 0x1a, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/256dpi/gomqtt@v0.10.4/broker/backend.go:198 +0xe38 fp=0x400074be10 sp=0x400074bc20 pc=0x246f828
github.com/256dpi/gomqtt/broker.(*Client).processConnect(0x4001648000, 0x400157c050, 0xf, 0x4001648000)
	github.com/256dpi/gomqtt@v0.10.4/broker/client.go:514 +0x138 fp=0x400074bec0 sp=0x400074be10 pc=0x2471d78
github.com/256dpi/gomqtt/broker.(*Client).processor(0x4001648000, 0x246a9ec, 0x4000022ec0)
	github.com/256dpi/gomqtt@v0.10.4/broker/client.go:325 +0xf4 fp=0x400074bf40 sp=0x400074bec0 pc=0x24710d4
github.com/256dpi/gomqtt/broker.(*Client).processor-fm(0x0, 0xfc18a8)
	github.com/256dpi/gomqtt@v0.10.4/broker/client.go:307 +0x28 fp=0x400074bf70 sp=0x400074bf40 pc=0x2474db8
gopkg.in/tomb%2ev2.(*Tomb).run(0x4001648098, 0x4000468050)
	gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x34 fp=0x400074bfc0 sp=0x400074bf70 pc=0x246a964
runtime.goexit()
	runtime/asm_arm64.s:1148 +0x4 fp=0x400074bfc0 sp=0x400074bfc0 pc=0xfc18a4
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xc0
```

**Comment by 256dpi** [comment]
Without looking looking further I notice that you're using `gomqtt@v0.10.4` which is more than two years old. I suggest to update the library first and then try again, if the bug is reproducible.

**Comment by yukunQin** [comment]
hi @256dpi ,  
    The bug is difficult to reproduce, and I have compared to the latest version, there are few changes.
     I look into the code， and find a doubts， can you help me to check it?
     in Client processor goroutine，
         func (m *MemoryBackend) Setup(client *Client, id string, clean bool) (Session, bool, error) {
                 ....
             	**existingSession.owner.Close()**

		// release global mutex to allow publish and termination, but leave the
		// setup mutex to prevent setups
		m.globalMutex.Unlock()

		// wait for client to close
		var err error
		select {
		**case <-existingSession.owner.Closed():**
			// continue
		case <-time.After(m.KillTimeout):
			err = ErrKillTimeout
		}
                ....
          }

         _existingSession.owner.Close()_  trigger to close the client, so in another goroutine (the cleanup goroutine), it would make the _owner_ point to nil(show below), so there's a certain probability the _existingSession.owner_ become nil, and then to execute the _case <-existingSession.owner.Closed()_ .

        func (m *MemoryBackend) Terminate(client *Client) error {
	        // acquire global mutex
	        m.globalMutex.Lock()
	        defer m.globalMutex.Unlock()
        
	        // release session if available
	        sess, ok := client.Session().(*memorySession)
	        if ok && sess != nil {
		        **sess.owner = nil**
	        }
               ....
           }

Thanks.

**Comment by yukunQin** [comment]
hi @256dpi ,
The bug is difficult to reproduce, and I have compared to the latest version, there are few changes.
I look into the code， and find a doubts， can you help me to check it?
in Client processor goroutine，
```
func (m *MemoryBackend) Setup(client *Client, id string, clean bool) (Session, bool, error) {
         ....
        existingSession.owner.Close()   // **trigger the client to close**

	// release global mutex to allow publish and termination, but leave the
	// setup mutex to prevent setups
	m.globalMutex.Unlock()

	// wait for client to close
	var err error
	select {
	case <-existingSession.owner.Closed():   // **when waiting the client closed, the owner may be made to nil**
		// continue
	case <-time.After(m.KillTimeout):
		err = ErrKillTimeout
	}
            ....
      }
```

_existingSession.owner.Close()_  trigger to close the client, so in another goroutine (the cleanup goroutine), it would make the _owner_ point to nil(show below), so there's a certain probability the _existingSession.owner_ become nil, and then to execute the _case <-existingSession.owner.Closed()_ .
```
 func (m *MemoryBackend) Terminate(client *Client) error {
        // acquire global mutex
        m.globalMutex.Lock()
        defer m.globalMutex.Unlock()
    
        // release session if available
        sess, ok := client.Session().(*memorySession)
        if ok && sess != nil {
	        sess.owner = nil   // **the owner would be setted to nil  here**
        }
           ....
 }
```

Thanks.

**Comment by 256dpi** [comment]
That is definitely a race condition. I just committed a fix for this issue.

**Comment by yukunQin** [comment]
fantastic job, well done!
