### ISSUE TITLE
Public client.tracker and support mqtt server bridge

### ISSUE THREAD

**Issue by ludanfeng** [256dpi/gomqtt#7]
gomqtt is a very good libs and used in our projects, thank all gomqtt contributors. But because some logics of our projects are different from gomqtt's, we cannot use some gomqtt's public structs directly. For example, we need a mqtt client with auto-reconnect feature and without any message cache in memory, so we must implement it by myself and in order to avoid to copy code we hope gomqtt/client/tracker can be marked as a public struct.

**Comment by ludanfeng** [comment]
[CR](https://github.com/256dpi/gomqtt/pull/8#issue-212842798)

**Comment by 256dpi** [comment]
You said one reason ist that you need auto-reconnect. Did you look at the client.Service to use instead?

**Comment by 256dpi** [comment]
In this case, I would also use the `transport` package and craft a "bridging" client myself (the same thing you do by altering the `client` package). That way you should be able to create "passthrough" like behaviour you're describing. This client is probably much simpler as it does not need any futures and callback stuff.

If you can share/contribute you work. I'm happy to add this as a `gomqtt-bridge` CLI tool in this project for any future users.

**Comment by ludanfeng** [comment]
Yes, [CR](https://github.com/256dpi/gomqtt/pull/9#issue-213965831)

**Comment by 256dpi** [comment]
I'm closing this due to age. Please reopen if you want to continue discussing the idea.
